# Generated by Django 5.2.8 on 2025-11-30 23:27

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcontractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company_name', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(choices=[('plumber', 'Plumber'), ('electrician', 'Electrician'), ('hvac', 'HVAC Technician'), ('cleaner', 'Cleaning Services'), ('security', 'Security'), ('landscaper', 'Landscaping'), ('painter', 'Painter'), ('carpenter', 'Carpenter'), ('pest_control', 'Pest Control'), ('general', 'General Maintenance')], max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('joined_date', models.DateField(default=datetime.date.today)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='resident',
            name='monthly_rent',
            field=models.DecimalField(decimal_places=2, default=10000.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='resident',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('moved_out', 'Moved Out')], default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='ParkingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.CharField(max_length=10, unique=True)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('available', 'Available')], default='available', max_length=20)),
                ('assigned_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('resident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parking_slots', to='dashboard.resident')),
            ],
            options={
                'ordering': ['slot_number'],
            },
        ),
    ]
