# Generated by Django 5.2.8 on 2025-11-28 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='monthly_rent',
            field=models.DecimalField(decimal_places=2, default=10000.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='resident',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('moved_out', 'Moved Out')], default='active', max_length=20),
        ),
    ]
