# Generated by Django 5.2.8 on 2025-11-29 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_resident_monthly_rent_resident_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.CharField(max_length=10, unique=True)),
                ('unit_number', models.CharField(blank=True, max_length=10)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('available', 'Available')], default='available', max_length=20)),
                ('assigned_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['slot_number'],
            },
        ),
    ]
