# Generated by Django 5.2.8 on 2025-11-29 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_parkingslot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingslot',
            name='unit_number',
        ),
        migrations.AddField(
            model_name='parkingslot',
            name='resident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parking_slots', to='dashboard.resident'),
        ),
    ]
