# Generated by Django 5.2.8 on 2025-11-30 00:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_parkingslot_unit_number_parkingslot_resident'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcontractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company_name', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(choices=[('plumber', 'Plumber'), ('electrician', 'Electrician'), ('hvac', 'HVAC Technician'), ('cleaner', 'Cleaning Services'), ('security', 'Security'), ('landscaper', 'Landscaping'), ('painter', 'Painter'), ('carpenter', 'Carpenter'), ('pest_control', 'Pest Control'), ('general', 'General Maintenance')], max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('joined_date', models.DateField(default=datetime.date.today)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
