# Generated by Django 5.2.8 on 2025-12-01 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_subcontractor_resident_monthly_rent_resident_status_and_more'),
        ('dashboard', '0005_subcontractor'),
    ]

    operations = [
    ]
