# Generated by Django 5.2.8 on 2025-12-01 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_payment_options_payment_amount_paid_and_more'),
    ]

    operations = [
    ]
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0007_alter_payment_options_payment_amount_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='month',
            field=models.CharField(default='', max_length=20),
        ),
    ]