# Generated by Django 5.2.8 on 2025-12-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_unit_options_unit_created_at_unit_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={},
        ),
        migrations.RemoveField(
            model_name='unit',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='last_maintenance',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='resident',
        ),
        migrations.AlterField(
            model_name='unit',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='floor',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='unit',
            name='rent_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='unit',
            name='size_sqm',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_type',
            field=models.CharField(choices=[('studio', 'Studio'), ('1br', '1 Bedroom'), ('2br', '2 Bedrooms'), ('3br', '3 Bedrooms'), ('4br', '4 Bedrooms')], default='1br', max_length=10),
        ),
    ]
